export const todayData = [
  {
    id: 0,
    title: 'Total Customers',
    value: 324,
    textColor: 'text-blue-500',
  },
  {
    id: 1,
    title: 'Total Transactions',
    value: 10000,
    textColor: 'text-yellow-500',
  },
  {
    id: 2,
    title: 'Cash Transactions',
    value: 8000,
    textColor: 'text-green-500',
  },
  {
    id: 3,
    title: 'credit Transactions',
    value: 8000,
    textColor: 'text-red-500',
  },
]

export const recentActivityData = [
  {
    id: 0,
    customerName: 'Sunita Gautam ',
    transationOn: 'credit',
    amount: '1500',
    time: '2024-04-15 10:30 AM',
  },
  {
    id: 1,
    customerName: 'Suresh Dahal',
    transationOn: 'cash',
    amount: '300',
    time: '2024-04-15 10:30 AM',
  },
  {
    id: 2,
    customerName: 'Sunita Gautam ',
    transationOn: 'cash',
    amount: '500',
    time: '2024-04-15 10:30 AM',
  },
  {
    id: 3,
    customerName: 'Ram Lamichhane',
    transationOn: 'credit',
    amount: '15000',
    time: '2024-04-15 10:30 AM',
  },
  {
    id: 4,
    customerName: 'Sunita Gautam ',
    transationOn: 'credit',
    amount: '1500',
    time: '2024-04-15 10:30 AM',
  },
  {
    id: 5,
    customerName: 'Suresh Dahal',
    transationOn: 'cash',
    amount: '300',
    time: '2024-04-15 10:30 AM',
  },
  {
    id: 6,
    customerName: 'Sunita Gautam ',
    transationOn: 'cash',
    amount: '500',
    time: '2024-04-15 10:30 AM',
  },
  {
    id: 7,
    customerName: 'Ram Lamichhane',
    transationOn: 'credit',
    amount: '15000',
    time: '2024-04-15 10:30 AM',
  },
]

export const chartData = [
  { name: '6 AM', value: 400 },
  { name: '7 AM', value: 300 },
  { name: '8 AM', value: 600 },
  { name: '9 AM', value: 500 },
  { name: '10 AM', value: 800 },
  { name: '11 AM ', value: 700 },
  { name: '12 PM', value: 900 },
  { name: '1 PM', value: 200 },
  { name: '2 PM', value: 800 },
  { name: '3 PM ', value: 700 },
  { name: '4 PM', value: 900 },
  { name: '5 PM', value: 200 },
  { name: '6 PM', value: 200 },
  { name: '7 PM', value: 800 },
  { name: '8 PM ', value: 700 },
]

export const lowStockProducts = [
  {
    id: 1,
    name: 'Organic Whole Milk',
    currentStockLevel: 5,
    reorderLevel: 10,
    supplier: 'Fresh Farms Dairy',
    lastPurchaseDate: '2024-04-10',
  },
  {
    id: 2,
    name: 'Whole Grain Bread',
    currentStockLevel: 3,
    reorderLevel: 10,
    supplier: `Baker's Delight`,
    lastPurchaseDate: '2024-04-05',
  },
  {
    id: 3,
    name: 'Free-Range Eggs (Dozen)',
    currentStockLevel: 2,
    reorderLevel: 10,
    supplier: 'Happy Hen Farms',
    lastPurchaseDate: '2024-03-28',
  },
  {
    id: 4,
    name: 'Fresh Organic Spinach',
    currentStockLevel: 0,
    reorderLevel: 10,
    supplier: 'Green Leaf Produce',
    lastPurchaseDate: '2024-04-10',
  },
  {
    id: 5,
    name: 'Handcrafted Artisanal Cheese',
    currentStockLevel: 3,
    reorderLevel: 10,
    supplier: 'Cheese Cave Creamery',
    lastPurchaseDate: '2024-04-05',
  },
  {
    id: 6,
    name: 'Grass-Fed Beef Steaks ',
    currentStockLevel: 0,
    reorderLevel: 10,
    supplier: 'Pasture Prime Meats',
    lastPurchaseDate: '2024-03-28',
  },
  {
    id: 7,
    name: 'Organic Whole Milk',
    currentStockLevel: 5,
    reorderLevel: 10,
    supplier: 'Fresh Farms Dairy',
    lastPurchaseDate: '2024-04-10',
  },
  {
    id: 8,
    name: 'Whole Grain Bread',
    currentStockLevel: 3,
    reorderLevel: 10,
    supplier: `Baker's Delight`,
    lastPurchaseDate: '2024-04-05',
  },
  {
    id: 9,
    name: 'Free-Range Eggs (Dozen)',
    currentStockLevel: 2,
    reorderLevel: 10,
    supplier: 'Happy Hen Farms',
    lastPurchaseDate: '2024-03-28',
  },
  // Add more products as needed
]
